### ISSUE TITLE
Crash on Startup with mixin 0.8 being bundled with some mods, compatibility issue? 

### ISSUE THREAD

**Issue by Landiie** [Tfarcenim/HarvestCraftTweaker2#1]
been having this problem with this mod in my modpack, removing this mod allowed it to work just fine, but with it, it just doesn't want to boot. Oddly enough, this mod does not want to work with the latest vanillafix which uses mixin 0.8, reverting to an older version of vf loads the mod perfectly fine however.

tried using another mod that requires, and bundles in mixin 0.8, (plustweaks 1.4.7) but also gives the same crash. Plustweaks has an older version, 1.4.3, which bundles in the older 0.7.11 mixin, and harvestcraft tweaker works perfectly fine. 

the reoccurring trend seems to be these mods updating to mixin 0.8, hence the possibility of a compatibility issue?

hopefully you can investigate?

EDIT: Decided to set up some isolated environments. 

**[_CRASH_]** First environment is with AutoRegLib (CT Dependency), Crafttweaker, harvestcrafttweaker, pamsharvestcraft, and the latest VanillaFix version 1.0.10-150, crash log here [Crash with VanillaFix-1.0.10-150.](https://pastebin.com/CHyYDS3d) using mixin 0.8.

Second environment is the exact same as the first, with the only change being the version of vanillafix. Going from version 1.0.10-150 down to version 1.0.10-99. No crash, working perfectly. using mixin 0.7.11.

**[_CRASH_]** Third environment is the exact same as the first, with the only change being a swap of mods. Disabled vanillafix, and swapped it for a mod called [Plus Tweaks.](https://www.curseforge.com/minecraft/mc-mods/plus-tweaks) In this environment, i used plustweaks version 1.4.7. this also crashed, log here [Crash with Plus Tweaks 1.4.7.](https://pastebin.com/J7dF8Umi) using mixin 0.8. 

Fourth environment is the same as the third, however i use plustweaks 1.4.3 instead. No crash at all, works flawlessly. using mixin 0.7.11.

I love this mod to bits, this is the first time that harvestcraft actually gets crafttweaker support, and this is a must-have for modpacks that want to make harvestcraft so much more personalized and interesting! I want to use it, but i sadly cannot with this standing issue D:

Hope all this helps!!

**Comment by Tfarcenim** [comment]
nailed it down
