### ISSUE TITLE
Crash on startup again D:

### ISSUE THREAD

**Issue by Landsurfer2000** [Tfarcenim/HarvestCraftTweaker2#2]
Sadly it's crashed with the newest version put out (1.2a), here is my crash report [full log and crash](https://pastebin.com/cTspzj0U)

 I really appreciate that you are still going strong, please don't stress yourself out over it D:

**Comment by Tfarcenim** [comment]
good catch, I'll add it to the dependencies

**Comment by Landsurfer2000** [comment]
I dont think it being a dependency has an issue with it... i unfortunately still get the same crash on 1.2b :(

**Comment by Tfarcenim** [comment]
new log?

**Comment by Landsurfer2000** [comment]
no, same :c i realized i was using an older version of pam's harvestcraft but it didnt seem to change anything when i went to the newest version [log](https://pastebin.com/UYP9qmC3)

**Comment by Tfarcenim** [comment]
what's the name of the harvestcraft jar?  seems like it's somehow not getting found

**Comment by Landsurfer2000** [comment]
Pam's+HarvestCraft+1.12.2zg.jar

**Comment by Tfarcenim** [comment]
fucking hell, no wonder it wasn't found

**Comment by Tfarcenim** [comment]
you know what? give me a sec, gonna post the new jar here before I bother making another pointless update to cf.

**Comment by Landsurfer2000** [comment]
oh, smart. Yeah ill help you test this

**Comment by Tfarcenim** [comment]
https://cdn.discordapp.com/attachments/559946769597857803/747786913209122866/harvestcrafttweaker-1.2c.jar here is the change
![image](https://user-images.githubusercontent.com/44327798/91171698-e939e080-e6a8-11ea-9911-67281438c66e.png)

**Comment by Landsurfer2000** [comment]
nice, ill give it a shot

**Comment by Landsurfer2000** [comment]
It loaded! I'll test some scripts and edit this comment if everything is going smoothly, but holy hell its awesome its working again! tysm <3

**Comment by Tfarcenim** [comment]
uploading now, hopefully this is the last time I have to do this
